### ISSUE TITLE
Help with chords names

### ISSUE THREAD

**Issue by oldcastlehq** [ldrolez/free-midi-chords#1]
Hi,

First, this is great! Well done!

I am a complete beginner in music production. I just had my first piano class, because I want to learn a bit of music to be able to make my EDM tracks. I have two questions:

1) I know is out of the scoop, but I am quite confused (because of my lack of knowledge) with some files names and their meaning. For example, what all those letters mean at C - bIIIM ii bIIM I.mid file? If you could just explain a bit the meaning of those letters would be fantastic and very appreciated.

2) Because I'm just starting, I don't want (and don't have money) to spend money on Ableton right now. So, I'm using free software (Qtractor). I've so far only worked with audio samples, so I'm new to MIDI. After I imported the MIDI file to my DAW, do I need to "add" an instrument to it or something? And my instrument, do you mean a vst plugin or something else?

Sorry for these sillies questions, but I hope you can help me kick off here.

Thank you a lot,
Castle

**Comment by ldrolez** [comment]
Hi!

Many thanks for your feedback!
Yes, I need to improve the documentation and that's the opportunity to start now :)

1- About the file names:

The file you're referring to is a chord progression. C is the key, C major if the file is in the 'major' directory. The following roman numbers are the degrees of the chords in the scale. 'I' is the first chord of the scale, so it's a C Major chord. 'ii' is a minor chord, the 2nd chord in the scale of C, so it a D minor chord. More info in this [here](https://en.wikipedia.org/wiki/Chord_(music)#Scale_degree)
For example, the chord progression file 'C - I V VI iv' is one of the [most popular chord progressions](https://en.wikipedia.org/wiki/I%E2%80%93V%E2%80%93vi%E2%80%93IV_progression) and it will sound familiar to your ears.
The other chords in this progression are '[borrowed](https://en.wikipedia.org/wiki/Borrowed_chord)' chords from other scales. For example, bIIIM, is a Major chord with the root on E flat (Eb) which comes from the C minor scale. Mixing the notes from Major and Minor scales is often used to provide more 'color' and variety in songs.

2- About Qtractor and MIDI files

Yes, you need to add an instrument plugin to the track in order to render the MIDI notes to audio. There are tons of free MIDI instruments available, like sfz players or emulations of famous synths such as [Dexed](https://asb2m10.github.io/dexed/).

Have fun!

**Comment by oldcastlehq** [comment]
Great!

I'm enjoying playing with the midis.

Thank you a lot!
Cheers,
