### ISSUE TITLE
[new chord progression] Major I II IV I - Lydian mode

### ISSUE THREAD

**Issue by marcelocg** [ldrolez/free-midi-chords#16]
** Which Chord progression would you like to add to the pack? **

I II IV I - Although the II is a major chord, this is indeed a Major key progression, only in Lydian mode.

See David Bennett's video at https://youtu.be/5ANjO8ypYfQ

---------------

Hi, @ldrolez 

Thank you so much for putting this all together. How can I help you expanding this set even more? I am a developer myself with some Python knowledge and I think I can help on that side of things. As I have just stumbled upon this repo, I am not sure how thinks could/should be organized. With some guidance from you on the best way to contribute I can give it a try.

**Comment by ldrolez** [comment]
Thanks! Interesting chord progression and video 😃

**Comment by ldrolez** [comment]
> As I have just stumbled upon this repo, I am not sure how thinks could/should be organized. With some guidance from you on the best way to contribute I can give it a try.
Most of the work is done by https://github.com/Miserlou/chords2midi,
and I think that the algorithm for making the inversions could be improved https://github.com/ldrolez/free-midi-chords/blob/c653d4c3b5b5797d608d9eff97108afc83a8045e/src/chords2midi/c2m.py#L231 
For example 9th chords do not sound always good because the 9th is played one octave lower

**Comment by ldrolez** [comment]
Added the variant with IIM7 :)
